### ISSUE TITLE
Compatibility with Pandas 2

### ISSUE THREAD

**Issue by EXJUSTICE** [predict-idlab/tsflex#112]
Hi

Are there plans to include compatibility to address Pandas versions above 2.00? Currently tsflex cannot be used.

**Comment by jvdd** [comment]
Hey @EXJUSTICE,

Thanks for submitting this issue!

This is certainly a top priority for us! I will look into this ASAP - once #109 is merged, we will create a new release in which we hope to tackle this issue as well!

I will keep you posted in this issue!

Cheers, Jeroen
