### ISSUE TITLE
Get features for each line

### ISSUE THREAD

**Issue by IKetchup** [predict-idlab/tsflex#60]
Hello,

I would like to generate features for each observation of my time serie and not only window by window.

Does this possibility exist in tsfex and do you know how to do it ?

Thanks in advance

**Comment by jvdd** [comment]
Hi @IKetchup,

If I understand correctly you want to calculate features over a certain window, with a stride (= step) of 1 observation?
This can conveniently be realize with `tsflex`, as we have separate arguments for window(s) and stride(s)!  

See adapted version of our readme example;
```python
iimport pandas as pd; import numpy as np; import scipy.stats as ss
from tsflex.features import MultipleFeatureDescriptors, FeatureCollection
from tsflex.utils.data import load_empatica_data

# 1. Load sequence-indexed data (in this case a time-index)
df_tmp, df_acc, = load_empatica_data(['tmp', 'acc'])

# 2. Construct your feature extraction configuration
fc = FeatureCollection(
    MultipleFeatureDescriptors(
          functions=[np.min, np.max, np.mean],
          series_names=["TMP", "ACC_x", "ACC_y"],
          windows=[10, 50],  # your window size(s)
          strides=1,  # step op 1 sample
    )
)

# 3. Extract features
fc.calculate(data=[df_tmp, df_acc], show_progress=True)
```

---

However, if you were to calculate basic functions (such as mean, min, std, ...), I would suggest you to look at [`pd.DataFrame.rolling`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html) and its natively supported functions. But, once you use not natively supported functions (e.g. skew), you should use [`.apply`](https://pandas.pydata.org/docs/user_guide/window.html#rolling-apply) with `raw`=True -> the runtime will be on par with `tsflex`. 

See for yourself with this code;
```python
%timeit df_tmp.rolling(window=10).std()  # 1.37 ms
%timeit df_tmp.rolling(window=10).apply(np.std, raw=True)  # 729 ms  -  on par with tsflex
```

---

Once you calculate features with step > 1 => `tsflex` will outscale `pandas` its solutions significantly.

Hope this answer helps you!

(also I suppose you mean `tsflex` and not `tsfel`)

**Comment by jonasvdd** [comment]
Seems like @jvdd answered your question, hence I will close this issue @IKetchup!

**Comment by IKetchup** [comment]
Thanks for the great answer @jvdd !!
