### ISSUE TITLE
Feature extraction with an identifier

### ISSUE THREAD

**Issue by jvdd** [predict-idlab/tsflex#63]
Perform feature extraction with an identifier / group column.

Some example use cases; your data is a long table format of time series from;
* Multiple patients
* Multiple measurements / runs / samples

Credits @JarneVerhaeghe

**Comment by firmai** [comment]
Agree this one would be great

**Comment by arturdaraujo** [comment]
This would be equivalent to columns_id in tsfresh, I was also wondering if the functionality existed in tsflex. Awesome library by the way.

**Comment by d1bevz** [comment]
Totally agree, many plusses
