### ISSUE TITLE
pandas deprecationwarning - TimeStridedRolling

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/tsflex#69]
![image](https://user-images.githubusercontent.com/38005924/174549824-23b5708d-43ae-4c1a-b971-5eb62ba324b9.png)

![image](https://user-images.githubusercontent.com/38005924/174550243-2186c11c-55d4-4d00-8bab-fafba4e4e3c5.png)

"closed"=None => "inclusive=None

**Comment by jvdd** [comment]
Isn't this what PR #64 fixes?

**Comment by jonasvdd** [comment]
Indeed! my-bad!
